### ISSUE TITLE
Support for patches

### ISSUE THREAD

**Issue by Ammako** [hippie68/gogcheck#4]
It sounds like patches aren't supported.

Example: `patch_cyberpunk_2077_2.0_(67690)_to_Build_4902785Change_6408866_with_EP1_RL_(67718).exe`

Without unrar, the script complains that you need unrar. With unrar, it exits with no output.

Are patches even digitally signed, actually?

**Comment by hippie68** [comment]
Thanks for mentioning this. I will add patch support to the script soon. For now you should be able to check patches by using option `-f`. The message about missing unrar is just a warning, which admittedly seems out of place when nothing else happens. unrar is optional, and if the script encounters actual RAR files it will mention them separately whether unrar is present or not.
