### ISSUE TITLE
New digital signature serial number?

### ISSUE THREAD

**Issue by k0zyrev** [hippie68/gogcheck#7]
I've stumbled upon a recent upload (1 month old) which has signature's serial number not previously seen 0bad5d6bf5ce1ef257dafb8b75be92b2 - can anyone check if it's authentic? For some reason the issuer is called "Sectigo RSA Time Stamping Signer #4" instead of digicert, so it's a bit suspicious.

https://lenp.pardesicat.xyz/G21DoCu0

**Comment by Ammako** [comment]
Doesn't check out to me?

![image](https://github.com/user-attachments/assets/4b1ca8ae-cf97-4ff1-88f9-b3fdd5d49fc4)

**Comment by ghost** [comment]
Verified that atleast the two installers for Resident Evil 1 and 2 are using this serial.
Time to add 0bad5d6bf5ce1ef257dafb8b75be92b2 to the verified list?

Name
GOG sp. z o.o
Status
Valid
Issuer
DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
Valid From
12:00 AM 03/07/2024
Valid To
11:59 PM 03/19/2025
Valid Usage
Code Signing
Algorithm
sha256RSA
Thumbprint
AED404C86C5A1327B267355AB201A1197E0DAA66
Serial Number
0B AD 5D 6B F5 CE 1E F2 57 DA FB 8B 75 BE 92 B2

**Comment by hippie68** [comment]
It took a while for me to see the new signatures, too. Now that they are showing up in games that are part of the new GOG Preservation Program I have added the strings to the script.
